export enum LiveEventType {
  EVALUATION_SUBMITTED = 'EVALUATION_SUBMITTED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  ANNOUNCEMENT_PUBLISHED = 'ANNOUNCEMENT_PUBLISHED',
  LEADERBOARD_PUBLISHED = 'LEADERBOARD_PUBLISHED',
  TEAM_REGISTERED = 'TEAM_REGISTERED',
  TEAM_UPDATED = 'TEAM_UPDATED',
  SESSION_STARTED = 'SESSION_STARTED',
  SESSION_PAUSED = 'SESSION_PAUSED',
  SESSION_LOCKED = 'SESSION_LOCKED',
  EVENT_STATE_CHANGED = 'EVENT_STATE_CHANGED',
  NOTIFICATION_CREATED = 'NOTIFICATION_CREATED'
}
