import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Bell,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Eye,
  EyeOff,
  Home,
  Info,
  LayoutDashboard,
  LogOut,
  Menu,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Plus,
  Search,
  Settings,
  Shield,
  Star,
  Sun,
  Trophy,
  Upload,
  User,
  Users,
  X,
  XCircle,
  Loader2,
  Cpu,
  Leaf,
  Heart,
  Building,
  MapPin,
  Mail,
  Phone,
  Camera,
  Globe,
  Code,
  Link,
  Download,
  TrendingUp,
  TrendingDown,
  Minus,
  Activity,
  Smartphone,
  Zap,
  QrCode,
  RefreshCw,
  Maximize,
  Wifi,
  WifiOff,
  List,
  FileText,
  MessageCircle,
  type LucideIcon
} from 'lucide-react';

export type IconType = LucideIcon;

export const Icons = {
  // Core
  logo: Trophy,
  spinner: Loader2,
  
  // Navigation
  menu: Menu,
  close: X,
  home: Home,
  dashboard: LayoutDashboard,
  settings: Settings,
  logout: LogOut,
  
  // Users
  user: User,
  users: Users,
  
  // Actions
  add: Plus,
  search: Search,
  upload: Upload,
  download: Download,
  more: MoreHorizontal,
  moreVertical: MoreVertical,
  
  // Arrows & Chevrons
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  
  // Status & Feedback
  success: CheckCircle2,
  check: Check,
  error: XCircle,
  warning: AlertTriangle,
  info: Info,
  alert: AlertCircle,
  
  // Misc
  bell: Bell,
  clock: Clock,
  eye: Eye,
  eyeOff: EyeOff,
  shield: Shield,
  star: Star,
  sun: Sun,
  moon: Moon,
  trophy: Trophy,
  link: Link,
  
  // Tracks & Public Site
  cpu: Cpu,
  leaf: Leaf,
  heart: Heart,
  building: Building,
  mapPin: MapPin,
  mail: Mail,
  phone: Phone,
  instagram: Camera,
  linkedin: Globe,
  github: Code,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  minus: Minus,
  activity: Activity,
  smartphone: Smartphone,
  zap: Zap,
  qrCode: QrCode,
  refreshCw: RefreshCw,
  maximize: Maximize,
  wifi: Wifi,
  wifiOff: WifiOff,
  list: List,
  fileText: FileText,
  whatsapp: MessageCircle,
} as const;
